accountapp/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'), #class에서 함수를 뱉어주는 mothod = as_view  C R U D 패턴

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),#detail로 갔을때 로직을 실행해주어라 (트리거), pk primary key 고유값

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = "articleapp" #지정해 줘야 reverse_lazy 역산?

urlpatterns =[
    path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list')

]

ik_1ban_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')), #http 12903810293/profile/urls
    path('articles/', include('articleapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #파일경로 이기 때문에 별도로 설정 개발환경에서 미디어를 이용할 수 있음

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns =[
      path('create/', ProfileCreateView.as_view(), name='create'),
      path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

articleapp/models.py
from django.db import models

# Create your models here.

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(upload_to='profile/', null=True)
    nickname = models.CharField(max_length=30, unique=True)
    message = models.CharField(max_length=200, null=True)

accountapp/forms.py
#usercreationform 을 상속을 받아 커스터마이징 할것임
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm): #오버라이딩을 한다 accountcreationform == usercreationform Acc~~가 usercreaform을 상속한다.
    def __init__(self, *args, **kwargs):        #부모의 init를 상속
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True   #id = username (database),  user 라는 field를 못쓰게 하겠다

profileapp/forms.py
from django.forms import ModelForm
from profileapp.models import Profile

class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'nickname', 'message']

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld

@login_required
def hello_world(request):

    if request.method == 'POST':        #post get중 post로 오면

        temp = request.POST.get('hello_world_input')

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))


    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html',
                      context={'hello_world_list': hello_world_list})


# logic

class AccountCreateView(CreateView):        #createview 상속
    model = User
    form_class = UserCreationForm
    # success_url = reverse_lazy('accountapp:hello_world') #class에서는 reverse_lazy를 사용한다. (reverse와 같다)
    template_name = 'accountapp/create.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user' #????
    template_name = 'accountapp/detail.html'#페이지 가 있어야한다 routing - urls.py

has_ownership = [login_required, account_ownership_required]

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User                    #무엇을 업데이트 할 것인지
    form_class = AccountCreationForm   #1수정할 내용을 넣어준다. 따로 접근하지 않아도 됨 2커스터마이징을 해야함 상속 받아서
    context_object_name = 'target_user'
    # success_url = reverse_lazy('accountapp:hello_world')#일단은 헬로우월드
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    #탈퇴 폼클래스 필요 없음.
    context_object_name = 'target_user' #어떻게 사용할지 어떤객체를 지울 것인지
    success_url = reverse_lazy('accountapp:hello_world') #탈퇴 완료시 연결 url
    template_name = 'accountapp/delete.html' #어떤식으로 렌더링// urls.py에서 어떻게 접근할건지

articleapp/views.py
from django.shortcuts import render

# Create your views here.

profileapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from profileapp.decorators import profile_ownership_required
from profileapp.forms import ProfileCreationForm
from profileapp.models import Profile

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ProfileCreateView(CreateView):
    model = Profile
    form_class = ProfileCreationForm
    template_name = 'profileapp/create.html'


    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk' : self.object.user.pk})
@method_decorator(profile_ownership_required, 'get')
@method_decorator(profile_ownership_required, 'post')
class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileCreationForm
    context_object_name = 'target_profile'
    template_name = 'profileapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk' : self.object.user.pk})

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Sign up</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:create' %}" method="post"> {# url acc~app 의 create로 요청을 보내라 #}
                {% csrf_token %}   {# ??보안#}
                {% bootstrap_form form %}
                <div class="m-5"> {# 부모넓이 상송 #}
                    <input type="submit"
                           class="btn btn-dark rounded-pill px-5" > {# 출력버튼 px-5수평방향향#}
                </div>
            </form>
        </div>

    </div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{# {% load bootstrap4 %} form 사용하지 않음#}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Quit</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post"> {# url acc~app 의 create로 요청을 보내라 #}
                {% csrf_token %}   {# ??보안#}
{#                {% bootstrap_form form %}#}
                <div class="m-5"> {# 부모넓이 상송 #}
                    <input type="submit"
                           class="btn btn-danger rounded-pill px-5" > {# 출력버튼 px-5수평방향향#}
                </div>
            </form>
        </div>

    </div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="text-center mw-500 m-auto">
        <div class="m-5">
            {% if target_user.profile %}
                <img src ="{{ target_user.profile.image.url }}"
                     class="profile_image m-4"
                     alt="profile image"> {# alt 이미지를 안받을 때 대체로 넣는 것 #}
                <h2 class="NNS_B">
                    {{ target_user.profile.nickname }}
                        {% if user == target_user %}
                            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                            class="material-icons round_button">
                                handyman
                            </a>
                        {% endif %}
                </h2>
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
            <h2 class="NNS_B">
                <a href="{% url 'profileapp:create' %}">
                    Creation Profile
                </a>
            </h2>
            {% endif %}
        </div>
        <div>
            {{ target_user.date_joined }}
        </div>

        {% if user == target_user %}

        <div>
            <a href="{% url 'accountapp:update' pk=target_user.pk %}"
            class="material-icons round_button mx-1">
                settings
            </a>{# 나의정보수정페이지 이기 때문에 user의 plk #}

            <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
            class="material-icons round_button mx-1">
                close
            </a>{# 나의정보수정페이지 이기 때문에 user의 plk #}
        </div>
        {% endif %}
    </div>
{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}


    <div style="margin: 2rem; text-align: center">
        <h1>METHOD</h1>

        <form action="/accounts/hello_world/" method="post">
            {% csrf_token %}
            <input type="text" name="hello_world_input">
            <input type="submit"; class="px-5 btn btn-dark rounded-pill">
        </form>
        {%  for hello_world in hello_world_list %}
            <h3>{{ hello_world.text }}</h3>
        {% endfor %}
    </div>





{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Login</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:login' %}" method="post"> {# url acc~app 의 create로 요청을 보내라 #}
                {% csrf_token %}   {# ??보안#}
                {% bootstrap_form form %}
                <div class="m-5"> {# 부모넓이 상속 #}
                    <input type="submit"
                           class="btn btn-dark rounded-pill px-5" > {# 출력버튼 px-5수평방향향#}
                </div>
            </form>
        </div>

    </div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Update Info</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post"> {# url acc~app 의 create로 요청을 보내라 //어떤객체를 수정할 것인가/ 수정할 유저의 pk  #}
                {% csrf_token %}   {# ??보안#}
                {% bootstrap_form form %}
                <div class="m-5"> {# 부모넓이 상송 #}
                    <input type="submit"
                           class="btn btn-dark rounded-pill px-5" > {# 출력버튼 px-5수평방향향#}
                </div>
            </form>
        </div>

    </div>
{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .container div {
          width: 280px;
          background-color: antiquewhite;
          display: flex;
          justify-content: center;
          align-items: center;
          border-radius: 8px;
    }

        div img{
            width: 100%;
            border-radius: 1rem;
        }

    </style>
<!DOCTYPE html>
<div class="container my-5">
  <div class="item1">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item2">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item3">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item4">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item5">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item6">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item7">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item8">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item9">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item10">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item11">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item12">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
  <div class="item13">
      <img src="https://picsum.photos/200/300" alt="">
  </div>
</div>

    <script src="{% static 'js/magicgrid.js' %}">

    </script>





{% endblock %}

profileapp/templates/profileapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Create Profile</h4>
        </div>
        <div>
            <form action="{% url 'profileapp:create' %}"
                  enctype="multipart/form-data"
                  method="post"> {# url acc~app 의 create로 요청을 보내라 #}

                {% csrf_token %}   {# ??보안#}
                {% bootstrap_form form %}
                <div class="m-5"> {# 부모넓이 상속 #}
                    <input type="submit"
                           class="btn btn-dark rounded-pill px-5" > {# 출력버튼 px-5수평방향향#}
                </div>
            </form>
        </div>

    </div>
{% endblock %}

profileapp/templates/profileapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Update Profile</h4>
        </div>
        <div>
            <form action="{% url 'profileapp:update' pk=target_profile.pk %}"
                  enctype="multipart/form-data"
                  method="post"> {# url acc~app 의 create로 요청을 보내라 #}

                {% csrf_token %}   {# ??보안#}
                {% bootstrap_form form %}
                <div class="m-5"> {# 부모넓이 상속 #}
                    <input type="submit"
                           class="btn btn-dark rounded-pill px-5" > {# 출력버튼 px-5수평방향향#}
                </div>
            </form>
        </div>

    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% include 'head.html' %}

<body style="font-family: 'NanumSquareL'">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}


</body>
</html>

templates/footer.html
<div style="text-align: center">
    <div class="pragmatic_footer_button">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스 소개</span>
    </div>
    <div class="pragmatic_footer_logo">
        <h5>Pragmatic</h5>
    </div>

</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {# BOOTSTRAP LINK   #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {# GOOGLE FONTS LINK Black Han Sans   #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">

    {#  DEFAULT CSS LINK  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css'%}">
    {#    MATERIAL ICONS LINK #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">



    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align: center">

    <div class="pragmatic_header_logo">
        <h1>Pragmatic</h1>
    </div>

    <div class="pragmatic_header_button">
        <span>nav1</span>
        <span>nav2</span>
{#        유저가 로그인 되어있지 않다면#}
        {% if not user.is_authenticated %}
        <span>
            <a href="{% url 'accountapp:login' %}">
                Login
            </a>
        </span>
        <span>
            <a href="{% url 'accountapp:create' %}">
                SignUp
            </a>
        </span>
        {% else %}
        <span>
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                MyPage
            </a>
        </span>
        <span>
            <a href="{% url 'accountapp:logout' %}">
                Logout
            </a>
        </span>


        {% endif %}
    </div>
</div>